import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { cn } from "@/lib/utils";
import { Header } from "@/components/Header";
import { Providers } from "@/contexts/Providers";

const kanit = Kanit({
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: {
        default: "Home",
        template: "%s | folkmoz",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    kanit.className,
                    "antialiased flex flex-col h-screen",
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Providers>
                        <Header />
                        <main className="pb-20">
                            <div className="container">{children}</div>
                        </main>
                    </Providers>
                </ThemeProvider>
            </body>
        </html>
    );
}
